##

TARGETS = IEEEComputing

TEXFILES = $(wildcard *.tex)
DVIS = $(addsuffix .dvi,$(TARGETS))

COPY = if test -r $*.toc; then cp $*.toc $*.toc.bak; fi 

all: $(DVIS)

%.dvi: %.tex 
	$(COPY) ; latex $<
	bibtex $*
	$(COPY) ; latex $<
	$(COPY) ; latex $<
	dvipdf $(TARGETS).dvi

clean:
	/bin/rm -f $(PDFS) *.dvi *.aux *.ps *~ *.log *.lot *.lof *.toc *.blg *.bbl url.sty

FORCE:

